export const SET_UPCOMING_ACTIVITY_LIST = 'SET_UPCOMING_ACTIVITY_LIST';
export const GET_CARD_WEEKLY_LIMIT = 'GET_CARD_WEEKLY_LIMIT';
export const SET_CARD_WEEKLY_LIMIT = 'SET_CARD_WEEKLY_LIMIT';
export const STORE_CARD_WEEKLY_LIMIT = 'STORE_CARD_WEEKLY_LIMIT';